### PR TITLE
Library of Congress Classification

### PR DESCRIPTION
**Pull request by kristenmills**
We now have Library of Congress Classification. Awww yeah.

### CODE REVIEW

**Comment by kristenmills** [comment]
So the tests error because Travis doesn't have Yaz so it errored on bundle. That's going to be a fun one.

**Comment by nickserv** [comment]
It seems like we'll need Travis to compile a custom version of Yaz and put it on the path before `bundle install` runs, if that's even possible.

**Comment by kristenmills** [comment]
We can do `before_install`. It's kay

**Comment by kristenmills** [comment]
Aw. Yeah.

**Pull request merged**
